### ISSUE TITLE
Problem with spaces in onelab filepath 

### ISSUE THREAD

**Issue by gituser789** [upb-lea/FEM_Magnetics_Toolbox#13]
**Describe the bug**
File path with spaces leads to filepath-failure

**To Reproduce**
1. Install FEMMT
2. First Run, Type 'C:/Program files/onelab/' for onelab-path 
3. See error when running the basic example

**Expected behavior**
FEMMT can find ONELAB

**Desktop (please complete the following information):**
Windows 10

**Additional content**
the filepath-check seems to be correct (program can find onelab.py), but when running the basic_example, this leads to an error.

**Comment by JonasHoelscher** [comment]
Fixed. Unknown commit.
