### ISSUE TITLE
Rename scale in results plot

### ISSUE THREAD

**Issue by gituser789** [upb-lea/FEM_Magnetics_Toolbox#19]
**Is your feature request related to a problem? Please describe.**
The scale labeling in the simulation result view is too confusing, see screenshot.
![image](https://user-images.githubusercontent.com/62549000/163140075-e917207f-b74d-4b6a-8156-6be3755d8472.png)

**Describe the solution you'd like**
Rename j2F - real part e.g. to Losses / W
Rename Magb - real part e.g. to Magnitude B-Field / T

**Comment by JonasHoelscher** [comment]
Fixed in Commit adafabd3ca683d71753fe6f5e19fbc423e6979e3.
