### ISSUE TITLE
Won't import on Python version 3.9

### ISSUE THREAD

**Issue by pleepleus** [upb-lea/FEM_Magnetics_Toolbox#96]
**Describe the bug**
In version 3.9, I get the following exception when I attempt to import the library.

```
TypeError: unsupported operand type(s) for |: '_GenericAlias' and 'type'
```

The ``|``` syntax for type hints requires at least 3.10.  

**To Reproduce**
pip install in python < 3.10 and try to import

**Expected behavior**
Should either import successfully or throw an installation error stating the need for Python 3.10 or greater.

**Screenshots**
![image](https://github.com/upb-lea/FEM_Magnetics_Toolbox/assets/93219693/382be67e-425b-48f7-9356-c5ac126116b3)

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by gituser789** [comment]
thanks!
As latest versions of Debian and Ubuntu use python version 3.11 and 3.12, and 3.10 was introduced more than 2 years ago, i think we can drop the support for older python versions.

Minimum requirement is now python 3.10.
